server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: teros-service-registry
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false